name: my_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # DEPENDENCIAS BASE
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3
  provider: ^6.1.5+1
  supabase_flutter: ^2.10.3
  file_picker: ^10.3.6
  url_launcher: ^6.3.2
  uuid: ^4.5.2
  multi_select_flutter: ^4.1.3
  google_fonts: ^6.3.2
  image_picker: ^1.2.1
  intl: ^0.20.2
  http: ^1.6.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1

  # DEPENDENCIAS DE CHAT
  get_it: ^9.0.5
  dio: ^5.9.0
  open_filex: ^4.7.0

  # ðŸ”¥ FIX: versiÃ³n compatible
  share_plus: ^12.0.1

  cached_network_image: ^3.4.1
  photo_view: ^0.15.0
  flutter_downloader: ^1.12.0
  flutter_pdfview: ^1.4.3
  webview_flutter: ^4.13.0
  flutter_chat_ui: ^2.9.1

  # ðŸ”¥ FIX: versiÃ³n compatible con intl 0.20.x
  syncfusion_flutter_pdfviewer: ^31.1.21

  flutter_local_notifications: ^19.5.0

  # ZEGO
  zego_uikit_prebuilt_call: ^4.21.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/
